name: "Check release notes generation"

permissions: read-all

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
    - uses: actions/checkout@v4
      with:
        # pull_request_target checks out the base branch by default
        ref: refs/pull/${{ steps.findPr.outputs.pr }}/merge
    - uses: cachix/install-nix-action@v23
      with:
        # nixpkgs commit is pinned so that it doesn't break
        # diffutils 3.9.0
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/4ecab3273592f27479a583fb6d975d4aba3486fe.tar.gz
    - name: Generate release notes
      run : |
        cd nixos/doc/manual
        nix-build release-notes/rl-2311/utils/generate-release-notes.nix   
    - name: Diff generated release notes
      run: |
        diff release-notes/rl-2311/rl-2311.section.md result/rl-2311.section.md
    - if: ${{ failure() }}
      run: |
        echo "::error :: Release notes could not be regenerated correctly. Fix it to make a smooth transition."
